### ISSUE TITLE
Items I upload don't appear

### ISSUE THREAD

**Issue by fenwick67** [fenwick67/mastofeed#5]
check out bscott@mastodon.cloud's TL.  Items uploaded by him do not appear.

**Comment by fenwick67** [comment]
fix as of 09a09eb65da0648ce9ff073e9e6bab518b1dd4b4

**Comment by realityfabric** [comment]
This issue is a bit vague, so let me know if I should create a new issue, but images in my feed show up as broken. Here's an example with just my avatar, but it happens with every image:
![image](https://user-images.githubusercontent.com/8910652/56096805-a73c4000-5ea1-11e9-9bd8-c11533b3895b.png)

In my feed reader (Thunderbird) my avatar doesn't appear in my atom feed, but images attached to posts do show up.

**Comment by fenwick67** [comment]
Hi @realityfabric, your feed seems to work for me no problem, so it's probably a client-side issue. Can you tell me what browser and OS you're using, and any extensions you're using? Also are you in a weird network situation (behind a proxy or TOR or something)?

**Comment by realityfabric** [comment]
Oop, it was the Privacy Badger extension. It was blocking `files.mastodon.social` but when I told it not to block that anymore the images loaded perfectly fine.

![image](https://user-images.githubusercontent.com/8910652/56101087-7970ee80-5ed5-11e9-8dd9-ce1c8bea81a6.png)
